### PR TITLE
Fix Mayhem Integration and Add Fuzzing for Typescript

### PR DESCRIPTION
**Pull request by Gediminas19**
I'm not totally sure if this fix works, because my own Mayhem account API rate is too low, so it stops before completing the entire test.

### CODE REVIEW

**Comment by Gediminas19** [comment]
@xansec

**Comment by xansec** [comment]
Hmm, I'd like to at least see the action succeed on your end, but I understand there's nothing you can do about the rate limit. Do you have a link for a workflow run that has progressed the furthest?

**Comment by Gediminas19** [comment]
@xansec Here are 2 times it got far:
- https://github.com/Gediminas19/tree-sitter/runs/6852839469?check_suite_focus=true
- https://github.com/Gediminas19/tree-sitter/runs/6853112633?check_suite_focus=true

In the first run linked above, it failed on `bash_fuzzer`, the 5th fuzzer with the error `ERROR: The API returned with error 400: CSRF token not in form.`. I was worried I did it wrong, so I reordered the order of the tests in the `.github/workflows/mayhem.yml` file. That run is the second one linked above, and it failed on `go_fuzzer`, the 5th fuzzer again, and with the same error. So I think the failures were not due to my Mayhem setup.

Also FYI, the main changes of this PR are:
- I added fuzzing for the typescript (and tsx) tree-sitter, which I originally skipped because the fuzzing scripts provided wouldn't work on them directly. Some preprocessing is needed to get it to work with the scripts, which I have added.
- I have modified the Mayhemfiles to match the settings of the `run-fuzzers` script (in the repo) more closely.

**Comment by xansec** [comment]
Ok, makes sense. I think you can get past that `CSRF Token Not in Form` error by adding a Mayhem token to your repo:
https://community.forallsecure.com/t/error-the-api-returned-with-error-400-csrf-token-not-in-form/360/7

Anyways, this looks ok to me. Merging.

**Comment by xansec** [comment]
It appears that the ruby-fuzzer is still failing. Can you check just that fuzzer?
https://github.com/mayhemheroes/tree-sitter/actions/runs/2496377442

**Comment by Gediminas19** [comment]
> It appears that the ruby-fuzzer is still failing. Can you check just that fuzzer? https://github.com/mayhemheroes/tree-sitter/actions/runs/2496377442

I took a look again, and sorry, I honestly cannot tell what's wrong. The error message suggests there's something wrong with the compiled executable, but when I built the Docker image and ran `ruby_fuzzer` locally, it appeared to work. There is an interesting thing that may be related to why Mayhem thinks it fails though; it appears to "freeze" for over 12 seconds before it starts printing out fuzzing results. All the other fuzzers (`bash_fuzzer`, `c_fuzzer`, etc) start printing things out immediately. Is there a reason why this would happen?

**Comment by Gediminas19** [comment]
Update: I increased the `timeout` field in `ruby_fuzzer.mayhemfile` from 10 to 20, and it seems to be working now. I presume this is because of the 12 second freeze being greater than 10, but less than 20. I'll make a new PR once I'm sure it works fully.

**Comment by Gediminas19** [comment]
@xansec the fix  for ruby-fuzzer worked, but there is a new problem: https://github.com/Gediminas19/tree-sitter/runs/6934947377?check_suite_focus=true

The stage that uploads SARIF files says that having 16 runs is too many, and the max is 15. What should I do?

**Comment by xansec** [comment]
Regarding the failing SARIF stage, I will probably just reduce the number of runs to get this under 15. Thanks for looking into the Ruby-Fuzzer!

**Pull request merged**
