### PR TITLE
Fixed Mayhem Integration After New Pulls from Upstream

### PR DESCRIPTION
**Pull request by Gediminas19**
^

### CODE REVIEW

**Comment by xansec** [comment]
I will merge for now and monitor if any other failures pop up.

**Comment by xansec** [comment]
The ruby fuzzer seemed to fail - could you please take a look?
https://mayhem.forallsecure.com/mayhemheroes/tree-sitter/ruby-fuzzer/1

**Comment by Gediminas19** [comment]
It won't let me view the page

**Comment by xansec** [comment]
I updated permissions - try again?

**Pull request merged**
